//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isidore.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isidore.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rhino
        ///
        ///mtllib Cube.mtl
        ///o object_1
        ///usemtl material1
        ///v -0.5 -0.5 -0.5
        ///v -0.5 -0.5 0.5
        ///v -0.5 0.5 -0.5
        ///v -0.5 0.5 0.5
        ///v -0.5 0.5 -0.5
        ///v -0.5 0.5 0.5
        ///v 0.5 0.5 -0.5
        ///v 0.5 0.5 0.5
        ///v 0.5 0.5 -0.5
        ///v 0.5 0.5 0.5
        ///v 0.5 -0.5 -0.5
        ///v 0.5 -0.5 0.5
        ///v 0.5 -0.5 -0.5
        ///v 0.5 -0.5 0.5
        ///v -0.5 -0.5 -0.5
        ///v -0.5 -0.5 0.5
        ///v -0.5 -0.5 -0.5
        ///v -0.5 0.5 -0.5
        ///v 0.5 -0.5 -0.5
        ///v 0.5 0.5 -0.5
        ///v -0.5 -0.5 0.5
        ///v 0.5 -0.5 0.5
        ///v -0.5 0.5 0.5
        ///v 0.5 0.5 0.5
        ///vt 1 0
        ///vt 1 1
        ///vt 0 0
        ///vt 0 1
        ///vt 1 0
        ///vt 1 1
        ///vt 0 0
        ///vt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cube {
            get {
                return ResourceManager.GetString("Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rhino
        ///
        ///mtllib FirTree1.mtl
        ///g Default
        ///o Fir_Tree
        ///usemtl Fir Tree
        ///v -1.710917711257935 1.657869696617127 0.5978056192398071
        ///v -1.623751878738403 1.46158504486084 0.338464081287384
        ///v -1.561988472938538 2.856461048126221 -0.1589622795581818
        ///v -1.545388579368591 1.973200798034668 -0.2203311026096344
        ///v -1.536586165428162 1.327430725097656 0.07912249863147736
        ///v -1.51815390586853 3.337469100952148 -0.2401825487613678
        ///v -1.501383900642395 1.826743125915527 0.6337707042694092
        ///v -1.459406495094299 1.498 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirTree1 {
            get {
                return ResourceManager.GetString("FirTree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rhino
        ///
        ///mtllib Pyramid.mtl
        ///g Default
        ///o object_1
        ///usemtl material1
        ///v 0.5 0 0.5
        ///v -0.5 0 0.5
        ///v 0 1 0
        ///v -0.5 0 0.5
        ///v -0.5 0 -0.5
        ///v 0 1 0
        ///v -0.5 0 -0.5
        ///v 0.5 0 -0.5
        ///v 0 1 0
        ///v 0.5 0 -0.5
        ///v 0.5 0 0.5
        ///v 0 1 0
        ///v 0.5 0 0.5
        ///v -0.5 0 0.5
        ///v -0.5 0 -0.5
        ///v 0.5 0 -0.5
        ///vt 1 0
        ///vt 0 0
        ///vt 0.5 1
        ///vt 1 1
        ///vt 1 0
        ///vt 0 0.5
        ///vt 1 0
        ///vt 0 0
        ///vt 0.5 1
        ///vt 0 0
        ///vt 0 1
        ///vt 1 0.5
        ///vt 1 1
        ///vt 0 1
        ///vt 0 0
        ///vt 1 0
        ///vn 0 0.4472135901451111 0.8944271802902222
        ///vn 0 0.4472135901451111 0.8944271802902222
        ///vn 0 0.44721 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pyramid {
            get {
                return ResourceManager.GetString("Pyramid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap R {
            get {
                object obj = ResourceManager.GetObject("R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rhino
        ///
        ///mtllib R3D.mtl
        ///o object_1
        ///usemtl material1
        ///v 0.202469140291214 0 0
        ///v 0.1906584352254868 0 -0.0213864017277956
        ///v 0.1763851195573807 0 -0.04336652904748917
        ///v 0.1601074486970902 0 -0.06408794224262238
        ///v 0.1436881721019745 0 -0.08049259334802628
        ///v 0.1225805133581162 0 -0.09463763982057571
        ///v 0.1006172820925713 0 -0.1000000014901161
        ///v 0.07775481045246124 0 -0.09420458972454071
        ///v 0.05911644175648689 0 -0.08182067424058914
        ///v 0.04021042212843895 0 -0.06303878873586655
        ///v 0.02538914233446121 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string R3D {
            get {
                return ResourceManager.GetString("R3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rhino
        ///
        ///mtllib TruckBroad.mtl
        ///g Rim
        ///o Rims
        ///usemtl Rims
        ///v 3.078107595443726 0.4334003329277039 0.7309888005256653
        ///v 3.209140777587891 0.5763979554176331 0.7309888005256653
        ///v 3.401435136795044 0.6017139554023743 0.7309889197349548
        ///v 3.565014123916626 0.4975026845932007 0.7309890985488892
        ///v 3.623337030410767 0.312525749206543 0.7309892773628235
        ///v 3.549114227294922 0.1333359330892563 0.7309893369674683
        ///v 3.3770751953125 0.04377811774611473 0.7309892773628235
        ///v 3.187718868255615 0.08575741946697235 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TruckBroad {
            get {
                return ResourceManager.GetString("TruckBroad", resourceCulture);
            }
        }
    }
}
